name: Generate Collage
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
    # Run the workflow every 24 hours - https://crontab.guru/#0_*/24_*_*_*
    - cron: '0 */24 * * *'

jobs:
  lint:
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Python
      run: |
        sudo apt-get update -y
        sudo apt-get install python3 imagemagick ffmpeg -y
        mkdir dist

    - name: Generate Images
      run: |
        python3 main.py --repo=csprite/csprite --exclude=fossabot --grid-width=6
        mv ./contributors.png dist/csprite-csprite.png

        python3 main.py --repo=csprite/languages --exclude=fossabot --grid-width=6
        mv ./contributors.png dist/csprite-languages.png

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist

